# Use the Debian stable image as the base
FROM debian:stable

ENV LC_ALL=C

# Update and install basic dependencies
RUN apt-get update && \
    apt-get install -y \
    gcc \
    coreutils \
    bc \
    bison \
    flex \
    make \
    cmake \
    gawk \
    file \
    xz-utils \
    bash \
    wget \
    cpio \
    ruby \
    libncurses-dev \
    libelf-dev \
    libssl-dev

# Grab the cross-compiler toolchain
RUN apt-get install -y \
    gcc-x86-64-linux-gnu \
    binutils-x86-64-linux-gnu \
    # TODO: Remove this once linking against prebuilt libc is no longer needed
    libc6-dev-amd64-cross

# Grab tools to create the bootable image
RUN apt-get install -y \
    syslinux-common \
    isolinux \
    genisoimage

# Ensure the shell is bash
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Keep the container running
CMD ["/bin/bash"]
